SELECT
  
  USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.NUM_ANO,
  USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.NUM_MES,
  USR_DW_EXEC_ORCAMENTARIA.DIM_UO.COD_UO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FUNCAO.COD_FUNCAO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_SUBFUNCAO.COD_SUBFUNCAO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_PROGRAMA.COD_PROGRAMA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ACAO_SUBTITULO.COD_ACAO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_PO.COD_PO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_PO.DES_PO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ESFERA.COD_ESFERA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_RESULTADO_EOF.COD_RESULTADO_EOF,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA.COD_ELEMENTO_DESPESA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA.DES_ELEMENTO_DESPESA_ATUAL,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.IDE_FONTE,
  CASE 
    WHEN SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 1, 1) = '0' 
        THEN SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 3) 
    ELSE SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 2) 
  END AS CO_FONTE_RECURSO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.DES_FONTE,
   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_DOTACAO_INICIAL),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_AUTORIZADO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_EMPENHADO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_LIQUIDADO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_PAGO_CONTROLE_EMPENHO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_INSCRITO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_NAO_PROC_CANCELADO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_PROC_CANCELADO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_PAGO),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_NAO_PROC_A_PAGAR),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_RP_PROC_A_PAGAR),   
sum(USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.VLR_PAGAMENTOS_TOTAIS)


FROM
  USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_UO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FUNCAO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_SUBFUNCAO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_PROGRAMA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ACAO_SUBTITULO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_PO,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ESFERA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_RESULTADO_EOF,
  USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA,
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE
WHERE
  ( USR_DW_EXEC_ORCAMENTARIA.DIM_FUNCAO.IDE_FUNCAO=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_FUNCAO  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_SUBFUNCAO.IDE_SUBFUNCAO=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_SUBFUNCAO  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_PROGRAMA.IDE_PROGRAMA=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_PROGRAMA  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_ACAO_SUBTITULO.IDE_ACAO_SUBTITULO=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_ACAO_SUBTITULO  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_UO.IDE_UO=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_UO  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_ESFERA.IDE_ESFERA=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_ESFERA  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.IDE_FONTE=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_FONTE  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA.IDE_ELEMENTO_DESPESA=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_ELEMENTO_DESPESA  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_RESULTADO_EOF.IDE_RESULTADO_EOF=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_RESULTADO_EOF  )
  AND  ( USR_DW_EXEC_ORCAMENTARIA.DIM_PO.IDE_PO=USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.IDE_PO  )
  AND  
  (
    
USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.NUM_ANO = TO_CHAR(SYSDATE, 'YYYY')
  
   AND
   USR_DW_EXEC_ORCAMENTARIA.DIM_UO.COD_UO  IN  ( '25917','33904','40904','55902','93102','24903','25915','38901','40901','93904'  )
  )
GROUP BY
  USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.NUM_ANO, 
  USR_DW_EXEC_ORCAMENTARIA.FT_EXEC_ORCAMENTARIA.NUM_MES, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_UO.COD_UO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_FUNCAO.COD_FUNCAO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_SUBFUNCAO.COD_SUBFUNCAO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_PROGRAMA.COD_PROGRAMA, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_ACAO_SUBTITULO.COD_ACAO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_PO.COD_PO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_PO.DES_PO, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_ESFERA.COD_ESFERA, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_RESULTADO_EOF.COD_RESULTADO_EOF, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA.COD_ELEMENTO_DESPESA, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_ELEMENTO_DESPESA.DES_ELEMENTO_DESPESA_ATUAL, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.IDE_FONTE, 
  CASE 
    WHEN SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 1, 1) = '0' 
        THEN SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 3) 
    ELSE SUBSTR(USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.COD_FONTE, 2) 
  END, 
  USR_DW_EXEC_ORCAMENTARIA.DIM_FONTE.DES_FONTE