-- Passo 6: Seleção final, aplicando os filtros do usuário sobre o resultado já calculado e densificado.
SELECT
    -- Todas as colunas descritivas e os valores do mês e acumulados
    ID_ANO,
    ID_MES,
    ID_UO,
    CO_UO,
    NO_UO,
    CO_NATUREZA_RECEITA2,
    NO_NATUREZA_RECEITA2,
    CO_FONTE_SOF,
    ID_GRUPO_FONTE,
    NO_GRUPO_FONTE,
    ID_FONTE_RECURSO,
    CO_FONTE_RECURSO,
    NO_FONTE_RECURSO,
    ID_ESFERA_ORCAMENTARIA,
    NO_ESFERA_ORCAMENTARIA,
    ID_IN_RESULTADO_RECEITA,
    NO_IN_RESULTADO_RECEITA,
    VA_PREV_INI_RECEITA_SALDO,
    VA_PREV_INI_RECEITA_ACUMULADO,
    VA_RECEITA_ORC_LIQ_SALDO,
    VA_RECEITA_ORC_LIQ_ACUMULADO,
    VA_PREV_ATU_RECEITA_SALDO,
    VA_PREV_ATU_RECEITA_ACUMULADO,
    VA_DEDUCOES_RECEITA_SALDO,
    VA_DEDUCOES_RECEITA_ACUMULADO,
    VA_RECEITA_ORC_BRUTA_SALDO,
    VA_RECEITA_ORC_BRUTA_ACUMULADO,
    VA_PREV_INI_RECEITA_MOV_LIQ,
    VA_PREV_INI_RECEITA_MOV_LIQ_ACUMULADO,
    VA_RECEITA_ORC_LIQ_MOV_LIQ,
    VA_RECEITA_ORC_LIQ_MOV_LIQ_ACUMULADO,
    VA_PREV_ATU_RECEITA_MOV_LIQ,
    VA_PREV_ATU_RECEITA_MOV_LIQ_ACUMULADO,
    VA_DEDUCOES_RECEITA_MOV_LIQ,
    VA_DEDUCOES_RECEITA_MOV_LIQ_ACUMULADO,
    VA_RECEITA_ORC_BRUTA_MOV_LIQ,
    VA_RECEITA_ORC_BRUTA_MOV_LIQ_ACUMULADO
FROM
(
    -- Passo 5: Aplica as funções de janela sobre os dados completos para calcular os valores acumulados.
    SELECT
        dados_completos.*,        
        SUM(VA_PREV_INI_RECEITA_SALDO) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_PREV_INI_RECEITA_ACUMULADO,
        SUM(VA_RECEITA_ORC_LIQ_SALDO) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_RECEITA_ORC_LIQ_ACUMULADO,
        SUM(VA_PREV_ATU_RECEITA_SALDO) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_PREV_ATU_RECEITA_ACUMULADO,
        SUM(VA_DEDUCOES_RECEITA_SALDO) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_DEDUCOES_RECEITA_ACUMULADO,
        SUM(VA_RECEITA_ORC_BRUTA_SALDO) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_RECEITA_ORC_BRUTA_ACUMULADO,
        SUM(VA_PREV_INI_RECEITA_MOV_LIQ) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_PREV_INI_RECEITA_MOV_LIQ_ACUMULADO,
        SUM(VA_RECEITA_ORC_LIQ_MOV_LIQ) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_RECEITA_ORC_LIQ_MOV_LIQ_ACUMULADO,
        SUM(VA_PREV_ATU_RECEITA_MOV_LIQ) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTaria, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_PREV_ATU_RECEITA_MOV_LIQ_ACUMULADO,
        SUM(VA_DEDUCOES_RECEITA_MOV_LIQ) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_DEDUCOES_RECEITA_MOV_LIQ_ACUMULADO,
        SUM(VA_RECEITA_ORC_BRUTA_MOV_LIQ) OVER (PARTITION BY ID_ANO, ID_UO, CO_UO, NO_UO, CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2, CO_FONTE_SOF, ID_GRUPO_FONTE, NO_GRUPO_FONTE, ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO, ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA, ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA ORDER BY ID_MES) AS VA_RECEITA_ORC_BRUTA_MOV_LIQ_ACUMULADO
    FROM 
    (
        -- Passo 4: Junta a grade completa com os dados reais, usando NVL para trocar nulos por zero onde não há movimentação.
        SELECT
            grade.ID_ANO,
            grade.ID_MES,
            grade.ID_UO,
            grade.CO_UO,
            grade.NO_UO,
            grade.CO_NATUREZA_RECEITA2,
            grade.NO_NATUREZA_RECEITA2,
            grade.CO_FONTE_SOF,
            grade.ID_GRUPO_FONTE,
            grade.NO_GRUPO_FONTE,
            grade.ID_FONTE_RECURSO,
            grade.CO_FONTE_RECURSO,
            grade.NO_FONTE_RECURSO,
            grade.ID_ESFERA_ORCAMENTARIA,
            grade.NO_ESFERA_ORCAMENTARIA,
            grade.ID_IN_RESULTADO_RECEITA,
            grade.NO_IN_RESULTADO_RECEITA,
            NVL(ft.VA_PREV_INI_RECEITA_SALDO, 0) AS VA_PREV_INI_RECEITA_SALDO,
            NVL(ft.VA_RECEITA_ORC_LIQ_SALDO, 0) AS VA_RECEITA_ORC_LIQ_SALDO,
            NVL(ft.VA_PREV_ATU_RECEITA_SALDO, 0) AS VA_PREV_ATU_RECEITA_SALDO,
            NVL(ft.VA_DEDUCOES_RECEITA_SALDO, 0) AS VA_DEDUCOES_RECEITA_SALDO,
            NVL(ft.VA_RECEITA_ORC_BRUTA_SALDO, 0) AS VA_RECEITA_ORC_BRUTA_SALDO,
            NVL(ft.VA_PREV_INI_RECEITA_MOV_LIQ, 0) AS VA_PREV_INI_RECEITA_MOV_LIQ,
            NVL(ft.VA_RECEITA_ORC_LIQ_MOV_LIQ, 0) AS VA_RECEITA_ORC_LIQ_MOV_LIQ,
            NVL(ft.VA_PREV_ATU_RECEITA_MOV_LIQ, 0) AS VA_PREV_ATU_RECEITA_MOV_LIQ,
            NVL(ft.VA_DEDUCOES_RECEITA_MOV_LIQ, 0) AS VA_DEDUCOES_RECEITA_MOV_LIQ,
            NVL(ft.VA_RECEITA_ORC_BRUTA_MOV_LIQ, 0) AS VA_RECEITA_ORC_BRUTA_MOV_LIQ
        FROM
        (
            -- Passo 3: Cria uma grade completa com todas as combinações de dimensões para todos os meses.
            SELECT *
            FROM
            (
                -- Passo 1: Seleciona todas as combinações únicas de dimensões que existem no ano.
                SELECT DISTINCT
                    ID_ANO,
                    ID_UO, CO_UO, NO_UO,
                    CO_NATUREZA_RECEITA2, NO_NATUREZA_RECEITA2,
                    CO_FONTE_SOF,
                    ID_GRUPO_FONTE, NO_GRUPO_FONTE,
                    ID_FONTE_RECURSO, CO_FONTE_RECURSO, NO_FONTE_RECURSO,
                    ID_ESFERA_ORCAMENTARIA, NO_ESFERA_ORCAMENTARIA,
                    ID_IN_RESULTADO_RECEITA, NO_IN_RESULTADO_RECEITA
                FROM USR_DW_TESOUROGERENCIAL.wf_receita_pivot
                WHERE ID_ANO = 2025 -- Filtro principal do ano
            ) dimensoes
            CROSS JOIN
            (
                -- Passo 2: Gera uma tabela com os meses de 1 a 12.
                SELECT LEVEL AS ID_MES
                FROM DUAL
                CONNECT BY LEVEL <= 12
            ) meses
        ) grade
        LEFT JOIN USR_DW_TESOUROGERENCIAL.wf_receita_pivot ft
            -- CORREÇÃO: A chave de junção agora inclui TODAS as colunas que definem uma linha única.
            ON grade.ID_ANO = ft.ID_ANO
            AND grade.ID_MES = ft.ID_MES
            AND grade.ID_UO = ft.ID_UO
           AND grade.CO_UO = ft.CO_UO
            AND grade.NO_UO = ft.NO_UO
            AND grade.CO_NATUREZA_RECEITA2 = ft.CO_NATUREZA_RECEITA2
            AND grade.NO_NATUREZA_RECEITA2 = ft.NO_NATUREZA_RECEITA2
            AND grade.CO_FONTE_SOF = ft.CO_FONTE_SOF
            AND grade.ID_GRUPO_FONTE = ft.ID_GRUPO_FONTE
            AND grade.NO_GRUPO_FONTE = ft.NO_GRUPO_FONTE
            AND grade.ID_FONTE_RECURSO = ft.ID_FONTE_RECURSO
            AND grade.CO_FONTE_RECURSO = ft.CO_FONTE_RECURSO
            AND grade.NO_FONTE_RECURSO = ft.NO_FONTE_RECURSO
            AND grade.ID_ESFERA_ORCAMENTARIA = ft.ID_ESFERA_ORCAMENTARIA
            AND grade.NO_ESFERA_ORCAMENTARIA = ft.NO_ESFERA_ORCAMENTARIA
            AND grade.ID_IN_RESULTADO_RECEITA = ft.ID_IN_RESULTADO_RECEITA
            AND grade.NO_IN_RESULTADO_RECEITA = ft.NO_IN_RESULTADO_RECEITA
    ) dados_completos
) resultado_final
-- Seus filtros finais vêm aqui. A consulta interna já calculou tudo para todos os meses.

ORDER BY
    ID_UO,
    CO_NATUREZA_RECEITA2,
    CO_FONTE_SOF
